/**
 * The request wizard's positions in Norwegian, for the letter the client gets.
 *
 * The wizard (src/app/request/[token]/page.tsx, WORKER_TYPES_BY_INDUSTRY) keeps
 * its positions in English, and the confirmation letter is Norwegian: it used
 * to tell a Norwegian firm "Stilling: Carpenter" (his test, 24 September 2026).
 * A position that is not here, or one the client typed himself, stays as it is.
 */
const POSITION_NB: Record<string, string> = {
  Electrician: "Elektriker",
  "Industrial electrician": "Industrielektriker",
  "Automation technician": "Automatiker",
  "Service technician": "Servicetekniker",
  "Low voltage technician": "Svakstrømstekniker",
  "Fiber optic technician": "Fibermontør",
  "Telecom technician": "Telekommunikasjonsmontør",
  "Solar installer": "Solcellemontør",
  Plumber: "Rørlegger",
  "HVAC technician": "VVS-tekniker",
  "Ventilation installer": "Ventilasjonsmontør",
  "Refrigeration technician": "Kuldetekniker",
  "Pipe fitter": "Rørmontør",
  "Sprinkler installer": "Sprinklermontør",
  Carpenter: "Tømrer",
  Formworker: "Forskalingssnekker",
  "Concrete worker": "Betongarbeider",
  "Steel fixer": "Armerer",
  "Construction worker": "Bygningsarbeider",
  Bricklayer: "Murer",
  Roofer: "Taktekker",
  Scaffolder: "Stillasbygger",
  "Drywall installer": "Gipsmontør",
  Painter: "Maler",
  "Tile layer": "Flislegger",
  "Floor layer": "Gulvlegger",
  "Insulation worker": "Isolatør",
  Plasterer: "Murpusser",
  "Demolition worker": "Rivearbeider",
  "General construction laborer": "Anleggsarbeider",
  Welder: "Sveiser",
  "TIG welder": "TIG-sveiser",
  "MIG/MAG welder": "MIG/MAG-sveiser",
  "Industrial mechanic": "Industrimekaniker",
  "CNC operator": "CNC-operatør",
  "Metal fabricator": "Platearbeider",
  "Pipe welder": "Rørsveiser",
  "Plate worker": "Platearbeider",
  "Sheet metal worker": "Blikkenslager",
  "Maintenance mechanic": "Vedlikeholdsmekaniker",
  Turner: "Dreier",
  "Mill operator": "Fresemaskinoperatør",
  "Truck driver": "Lastebilsjåfør",
  Driver: "Sjåfør",
  "Forklift operator": "Truckfører",
  "Warehouse worker": "Lagerarbeider",
  "Delivery driver": "Budsjåfør",
  "Terminal worker": "Terminalarbeider",
  "Picker/Packer": "Plukker og pakker",
  "Logistics coordinator": "Logistikkoordinator",
  "Bus driver": "Bussjåfør",
  "Van driver": "Varebilsjåfør",
  "Crane operator": "Kranfører",
  "Machine operator": "Maskinoperatør",
  "Production worker": "Produksjonsmedarbeider",
  "Industrial worker": "Industriarbeider",
  "Process operator": "Prosessoperatør",
  "Assembly worker": "Montør",
  "Packaging operator": "Pakkeoperatør",
  "Factory worker": "Fabrikkarbeider",
  "Excavator operator": "Gravemaskinfører",
  "Wheel loader operator": "Hjullasterfører",
  "Road worker": "Veiarbeider",
  "Asphalt worker": "Asfaltarbeider",
  "Tunnel worker": "Tunnelarbeider",
  Cleaner: "Renholder",
  "Industrial cleaner": "Industrirenholder",
  "Housekeeping staff": "Romservice",
  Janitor: "Vaktmester",
  "Window cleaner": "Vinduspusser",
  "Facility technician": "Driftstekniker",
  "Special cleaning operator": "Spesialrenholder",
  Chef: "Kokk",
  Cook: "Kokk",
  "Sous chef": "Souschef",
  "Pizza chef": "Pizzabaker",
  Baker: "Baker",
  "Kitchen assistant": "Kjøkkenassistent",
  Waiter: "Servitør",
  Dishwasher: "Oppvasker",
  Bartender: "Bartender",
  "Hotel receptionist": "Hotellresepsjonist",
  "Pastry chef": "Konditor",
  Nurse: "Sykepleier",
  "Practical nurse": "Helsefagarbeider",
  "Healthcare assistant": "Pleieassistent",
  "Care worker": "Omsorgsarbeider",
  "Elderly care worker": "Omsorgsarbeider i eldreomsorgen",
  "Personal assistant": "Personlig assistent",
  Physiotherapist: "Fysioterapeut",
};

const LOWER = Object.fromEntries(Object.entries(POSITION_NB).map(([k, v]) => [k.toLowerCase(), v]));

export function positionNb(position: string): string {
  const p = String(position ?? "").trim();
  return POSITION_NB[p] ?? LOWER[p.toLowerCase()] ?? p;
}
