/** Optional skill checkboxes keyed by exact trade/position labels (see `INDUSTRY_GROUPS` roles). */
export const ROLE_SKILLS: Record<string, string[]> = {
  // Building
  Carpenter: [
    "Framing / reisverk",
    "Roof construction",
    "Formwork for concrete",
    "Window and door installation",
    "Interior woodwork",
    "Roof boarding and cladding",
  ],
  Mason: [
    "Brick and block laying",
    "Stone masonry",
    "Render and plaster base coat",
    "Fireplace and chimney",
    "Foundation work",
    "Tile adhesive base",
  ],
  Plasterer: [
    "Interior wet plaster",
    "Exterior render",
    "Machine plastering",
    "Ceiling plaster",
    "Repair and patching",
    "Skim coat finish",
  ],
  Painter: [
    "Interior walls and ceilings",
    "Exterior facades",
    "Wood surface treatment",
    "Floor painting and lacquering",
    "Wallpaper installation",
    "Spray painting",
  ],
  Tiler: [
    "Floor tiling",
    "Wall tiling",
    "Wet room / bathroom tiling",
    "Large format tiles",
    "Natural stone",
    "Grout and waterproofing",
  ],
  Insulator: [
    "Roof insulation",
    "Wall insulation",
    "Pipe insulation",
    "Technical insulation",
    "Facade insulation (ETICS)",
    "Fire insulation",
  ],
  Drywaller: [
    "Stud wall framing",
    "Plasterboard installation",
    "Ceiling systems",
    "Fire-rated partitions",
    "Acoustic partitions",
    "Finishing and taping",
  ],
  Glazier: [
    "Window installation",
    "Glass facade / curtain wall",
    "Shower and bathroom glass",
    "Mirrors and interior glass",
    "Sealing and gaskets",
    "Safety glass handling",
  ],
  Roofer: [
    "Flat roof membrane",
    "Pitched roof tiles",
    "Metal roofing",
    "Gutters and drainage",
    "Roof waterproofing",
    "Green / sedum roof",
  ],
  Plumber: [
    "Hot and cold water installation",
    "Drainage and sewage",
    "Underfloor heating",
    "Bathroom installation",
    "Gas installation",
    "Heat pump connection",
  ],
  Pipefitter: [
    "Industrial pipe systems",
    "Steel pipe welding and fitting",
    "Pressure testing",
    "HVAC pipe systems",
    "Insulated pipe systems",
    "Marine piping",
  ],
  "Construction worker": [
    "General site labour",
    "Demolition",
    "Concrete work",
    "Material handling",
    "Scaffold assistance",
    "Site cleanup",
  ],

  // Infrastructure
  "Excavator operator": [
    "Trenching for pipes/cables",
    "Foundation excavation",
    "Road construction",
    "Mass excavation",
    "Slope stabilization",
    "GPS-guided excavation",
  ],
  "Concrete pump operator": [
    "Mobile pump operation",
    "Stationary pump operation",
    "Boom pump",
    "Wet concrete placement",
    "High-rise concrete pumping",
    "Pump cleaning and maintenance",
  ],
  "Civil labourer": [
    "Road base and asphalt prep",
    "Pipe laying assistance",
    "Concrete formwork assistance",
    "Compaction work",
    "Drainage installation",
    "General site labour",
  ],
  "Steel fixer": [
    "Rebar cutting and bending",
    "Foundation reinforcement",
    "Wall and column rebar",
    "Slab reinforcement",
    "Reading structural drawings",
    "Tying and placing rebar",
  ],
  "Concrete worker": [
    "Formwork assembly",
    "Concrete pouring and vibration",
    "Surface finishing",
    "Curing and protection",
    "Precast element handling",
    "Shotcrete",
  ],
  "Steel erector": [
    "Structural steel assembly",
    "Beam and column connection",
    "Bolting and alignment",
    "Crane signal",
    "Safety at height",
    "Reading steel drawings",
  ],
  Scaffolder: [
    "System scaffold (Layher/Rux)",
    "Facade scaffolding",
    "Industrial scaffolding",
    "Suspended scaffold",
    "Offshore scaffolding",
    "Scaffold inspection",
  ],

  // Welding
  "Welder MIG/MAG": [
    "Structural steel welding",
    "Sheet metal welding",
    "Pipe welding (non-coded)",
    "Positional welding",
    "Stainless steel MIG",
    "Welding inspection readiness",
  ],
  "Welder TIG": [
    "Stainless steel TIG",
    "Aluminium TIG",
    "Pipe root pass TIG",
    "Thin sheet TIG",
    "Orbital TIG",
    "Coded welder (ISO 9606)",
  ],
  "Pipe welder": [
    "Carbon steel pipe welding",
    "Stainless pipe welding",
    "High-pressure systems",
    "ISO 9606 / ASME coded",
    "Root pass and fill",
    "Offshore pipe welding",
  ],
  Boilermaker: [
    "Pressure vessel fabrication",
    "Heat exchanger work",
    "Tank construction",
    "NDT readiness",
    "Blueprint reading",
    "Heavy plate welding",
  ],
  "Sheet metal worker": [
    "Ventilation duct fabrication",
    "Facade cladding",
    "Gutters and flashings",
    "Stainless fabrication",
    "Roof sheet metal",
    "Precision cutting and folding",
  ],
  "Offshore welder": [
    "NORSOK M-101 compliance",
    "Subsea welding awareness",
    "Coded welding (multiple positions)",
    "Inspection and documentation",
    "Offshore safety (BOSIET/HUET)",
    "Working in confined spaces",
  ],

  // Electrical
  "Industrial electrician": [
    "Motor control and drives (VSD)",
    "PLC wiring and connection",
    "High voltage (over 1000V)",
    "Cable pulling and termination",
    "Panel building",
    "Maintenance and fault finding",
  ],
  "Building electrician": [
    "Low voltage installation",
    "Consumer unit / distribution board",
    "Socket and lighting circuits",
    "EV charger installation",
    "Fire alarm wiring",
    "Testing and inspection (NEK)",
  ],
  "Automation technician": [
    "PLC programming (Siemens/Allen-Bradley)",
    "SCADA systems",
    "Instrumentation calibration",
    "Control panel design",
    "Process automation",
    "Safety systems (SIL)",
  ],
  "Instrumentation technician": [
    "Loop checks and commissioning",
    "Transmitters and analyzers",
    "Control valve troubleshooting",
    "DCS / PLC I/O verification",
    "P&ID and loop diagram reading",
    "Functional safety (SIS) awareness",
  ],
  "HVAC technician": [
    "Ventilation duct installation",
    "Air handling units (AHU)",
    "Balancing and commissioning",
    "Heat recovery systems",
    "Refrigerant handling (F-gass)",
    "BMS integration",
  ],
  "Refrigeration technician": [
    "Commercial refrigeration",
    "Industrial cooling systems",
    "F-gas certification",
    "Heat pump installation",
    "Cold room construction",
    "Leak detection and repair",
  ],
  "Marine electrician": [
    "Ship electrical systems",
    "Navigation equipment",
    "High voltage marine",
    "Class society compliance",
    "Cable routing on vessels",
    "Automation and alarm systems",
  ],
  "Solar installer": [
    "Rooftop PV installation",
    "String inverter connection",
    "Battery storage systems",
    "Grid connection",
    "Structural mounting",
    "Performance testing",
  ],

  // Production
  "CNC operator": [
    "CNC milling",
    "CNC turning",
    "G-code reading and editing",
    "Tool setting and offsets",
    "Quality measurement",
    "Machine maintenance",
  ],
  "Machine operator": [
    "Production line operation",
    "Quality control checks",
    "Machine setup and changeover",
    "Preventive maintenance",
    "Safety compliance",
    "Reporting and logging",
  ],
  "Production worker": [
    "Assembly line work",
    "Packing and labelling",
    "Material feeding",
    "Visual inspection",
    "Lean / 5S practices",
    "Shift work capability",
  ],
  "Quality control": [
    "Dimensional inspection",
    "Visual inspection",
    "Documentation and reporting",
    "Non-conformance handling",
    "Calibration awareness",
    "ISO 9001 familiarity",
  ],
  "Maintenance technician": [
    "Preventive maintenance (PM)",
    "Mechanical fault finding",
    "Hydraulics and pneumatics",
    "Electrical troubleshooting",
    "CMMS system use",
    "Welding and fabrication",
  ],
  "Plant operator": [
    "Process plant operation",
    "DCS / control room",
    "Safety systems (PTW)",
    "Shift handover",
    "Environmental compliance",
    "Emergency response",
  ],

  // Logistics
  "Truck driver C/CE": [
    "Long distance transport",
    "Local distribution",
    "ADR / hazardous goods",
    "Refrigerated transport",
    "Crane truck (krokbil)",
    "Digital tachograph",
  ],
  "Bus driver D": [
    "Scheduled route service",
    "School transport",
    "Charter and tourism",
    "Passenger safety",
    "Accessibility assistance",
    "Route planning",
  ],
  "Delivery driver B": [
    "Last mile delivery",
    "Customer interaction",
    "Route optimization",
    "Parcel scanning",
    "Light van operation",
    "Time-sensitive delivery",
  ],
  "Forklift operator": [
    "Counterbalance forklift",
    "Reach truck",
    "Order picker",
    "Pallet jack (elektrisk)",
    "Cold storage operation",
    "Load securing",
  ],
  "Warehouse worker": [
    "Goods receiving",
    "Order picking",
    "Inventory counting",
    "WMS system use",
    "Packing and dispatch",
    "Heavy lifting",
  ],
  "Crane operator": [
    "Tower crane",
    "Mobile crane",
    "Overhead crane",
    "Lift planning",
    "Slinging and rigging",
    "Crane inspection",
  ],

  // Cleaning
  Cleaner: [
    "Office and commercial cleaning",
    "Industrial cleaning",
    "Window cleaning",
    "Floor maintenance (polishing/scrubbing)",
    "Chemical handling",
    "Night/weekend shifts",
  ],
  Janitor: [
    "Building maintenance",
    "Minor repairs",
    "Snow clearing",
    "Waste management",
    "Tenant support",
    "Key and access management",
  ],
  "Window cleaner": [
    "High-rise window cleaning (rope access)",
    "Platform/boom lift operation",
    "Interior glass cleaning",
    "Facade washing",
    "Safety at height",
    "Chemical use compliance",
  ],
  "Facility manager": [
    "Contractor coordination",
    "Maintenance planning",
    "Budget management",
    "HSE compliance",
    "Tenant relations",
    "Service contract oversight",
  ],

  // Hospitality
  Cook: [
    "Hot kitchen (varmkjøkken)",
    "Cold kitchen (kaldkjøkken)",
    "Bakery and pastry",
    "Volume cooking",
    "HACCP compliance",
    "Menu development",
  ],
  "Kitchen assistant": [
    "Food prep and chopping",
    "Dishwashing",
    "Stock rotation",
    "Cleaning and hygiene",
    "Assisting head chef",
    "Allergen awareness",
  ],
  Waiter: [
    "Table service",
    "Bar service",
    "Upselling and recommendations",
    "POS system use",
    "Banquet and event service",
    "Wine and beverage knowledge",
  ],
  "Hotel staff": [
    "Room cleaning and turnover",
    "Front desk reception",
    "Guest check-in/out",
    "Concierge assistance",
    "Laundry and linen",
    "Night audit",
  ],
  Receptionist: [
    "Front desk management",
    "Booking systems",
    "Guest/visitor handling",
    "Phone and email communication",
    "Administrative support",
    "Multi-tasking under pressure",
  ],

  // Automotive
  "Car mechanic": [
    "Engine diagnostics (OBD)",
    "Brake and suspension",
    "Gearbox and clutch",
    "Electrical fault finding",
    "Service and maintenance",
    "Tyre and wheel work",
  ],
  "Heavy equipment mechanic": [
    "Excavator and bulldozer repair",
    "Hydraulic system repair",
    "Engine overhaul",
    "Track and undercarriage",
    "Welding and fabrication",
    "Field service / on-site repair",
  ],
  "HGV mechanic": [
    "Truck engine service",
    "Brake systems (EBS/ABS)",
    "Trailer inspection",
    "Tachograph service",
    "Refrigeration unit service",
    "Workshop and roadside repair",
  ],
  "Auto body technician": [
    "Panel beating and straightening",
    "MIG welding on bodywork",
    "Filler and preparation",
    "Primer and paint",
    "Plastic repair",
    "Insurance damage repair",
  ],
  "Tire technician": [
    "Tyre fitting and balancing",
    "Seasonal changeover",
    "Wheel alignment",
    "Truck tyre service",
    "Puncture repair",
    "TPMS systems",
  ],

  // Offshore
  "Offshore scaffolder": [
    "NORSOK scaffold standard",
    "Offshore scaffold inspection",
    "Working at height offshore",
    "BOSIET / offshore survival",
    "Rope access awareness",
    "Confined space entry",
  ],
  "Offshore rigger": [
    "Crane rigging and slinging",
    "Lifting operations",
    "Banksman/signaller",
    "Cargo handling",
    "Deck operations",
    "Lifting equipment inspection",
  ],
  "Onshore process operator": [
    "Oil and gas process plant",
    "Valve and instrument operation",
    "Process safety (PTW)",
    "Gas detection awareness",
    "Emergency shutdown",
    "Shift operations",
  ],
  "ROV technician": [
    "ROV pilot/technician",
    "Subsea inspection",
    "Hydraulic systems",
    "Camera and sensor operation",
    "Fault finding offshore",
    "Documentation and reporting",
  ],

  // Fish Industry
  "Fish processing worker": [
    "Filleting and portioning",
    "Quality grading",
    "Packing and labelling",
    "Freezing line operation",
    "HACCP compliance",
    "High-speed repetitive work",
  ],
  "Fish farm worker": [
    "Feeding operations",
    "Fish health monitoring",
    "Net handling and changing",
    "Boat operation",
    "Mortality handling",
    "Environmental compliance",
  ],
  "Aquaculture technician": [
    "Water quality monitoring",
    "Fish health treatment",
    "Smolt production",
    "Vaccination",
    "Data recording",
    "Equipment maintenance",
  ],
  "Fish packer": [
    "Ice packing",
    "Box and crate filling",
    "Weight and labelling",
    "Cold storage work",
    "Export documentation",
    "Speed and accuracy",
  ],
  "Slaughterhouse worker": [
    "Stunning and bleeding",
    "Evisceration",
    "Grading and sorting",
    "Food hygiene compliance",
    "Cold chain maintenance",
    "Heavy physical work",
  ],
  "Salmon farmer": [
    "Cage feeding management",
    "Fish behavior observation",
    "Mortality and lice counting",
    "Feed adjustment",
    "Boat and equipment operation",
    "Record keeping",
  ],

  // General Labour
  "General labourer": [
    "Site cleanup and tidying",
    "Material loading and unloading",
    "Concrete mixing (small scale)",
    "Trenching assistance",
    "Traffic management",
    "Tool and equipment handling",
  ],
  Helper: [
    "Assisting skilled tradespeople",
    "Carrying and fetching materials",
    "Basic tool use",
    "Following instructions precisely",
    "Safety compliance",
    "Willing to learn on site",
  ],
};
