"use client";

import { FormEvent, useState } from "react";

export default function CandidateRequestPage() {
  const [email, setEmail] = useState("");
  const [gdpr, setGdpr] = useState(false);
  const [passport, setPassport] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const submit = async () => { setBusy(true); setError(""); const res = await fetch("/api/candidate-join-network", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, gdpr_consent: gdpr, eu_eea_passport_confirmed: passport }) }); const data = await res.json().catch(() => ({})); setBusy(false); if (!res.ok) return setError(data.error || "Please try again."); setConfirmOpen(false); setSent(true); };
  const onSubmit = (e: FormEvent) => { e.preventDefault(); if (!gdpr || !passport) return setError("Please complete both confirmations."); setConfirmOpen(true); };
  return <main className="min-h-[calc(100vh-72px)] bg-[#0D1B2A] px-6 py-14 text-white"><form onSubmit={onSubmit} className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-white/[0.04] p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#C9A84C]">Candidate profile request</p><h1 className="mt-3 text-3xl font-bold">Request to create your profile</h1>{sent ? <p className="mt-5 leading-relaxed text-white/75">Check your email. If the request was yours, use the link there to continue to the Recman profile-creation page. This email check helps prevent false accounts and supports GDPR compliance.</p> : <><p className="mt-3 text-white/70">Confirm your email, GDPR consent and EU/EEA passport before we send your secure continuation link.</p><label className="mt-6 block text-sm font-semibold">Email address<input required value={email} onChange={(e) => setEmail(e.target.value)} type="email" className="mt-2 w-full rounded-lg border border-white/20 bg-[#0D1B2A] px-3 py-3 text-white" /></label><label className="mt-5 flex gap-3 text-sm text-white/80"><input type="checkbox" checked={gdpr} onChange={(e) => setGdpr(e.target.checked)} />I consent to ArbeidMatch processing this request and my email in accordance with GDPR.</label><label className="mt-4 flex gap-3 text-sm text-white/80"><input type="checkbox" checked={passport} onChange={(e) => setPassport(e.target.checked)} />I confirm that I hold a valid EU/EEA passport.</label>{error ? <p className="mt-4 text-sm text-red-300">{error}</p> : null}<button disabled={busy} className="mt-7 rounded-lg bg-[#C9A84C] px-5 py-3 font-semibold text-[#0D1B2A]">{busy ? "Sending..." : "Request profile creation"}</button></> }</form>{confirmOpen ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 px-6"><div className="max-w-md rounded-2xl bg-[#0D1B2A] p-6"><h2 className="text-xl font-bold">Final passport confirmation</h2><p className="mt-3 text-white/75">Only candidates with a valid EU/EEA passport can be accepted. If this cannot be confirmed, the profile will not be accepted in our recruitment system.</p><div className="mt-6 flex gap-3"><button type="button" onClick={() => setConfirmOpen(false)} className="rounded-lg border border-white/20 px-4 py-2">Go back</button><button type="button" onClick={submit} disabled={busy} className="rounded-lg bg-[#C9A84C] px-4 py-2 font-semibold text-[#0D1B2A]">I confirm</button></div></div></div> : null}</main>;
}
