import type { JobRecord } from "@/lib/jobs/types";

const now = new Date().toISOString();

export const JOBS_MOCK_DATA: JobRecord[] = [
  {
    id: "manual-001",
    source: "manual",
    title: "Industrial Electrician, Oslo Rotation",
    slug: "industrial-electrician-oslo-rotation",
    companyName: null,
    hideCompany: true,
    location: "Oslo",
    category: "Electrical",
    trade: "Industrial Electrician",
    contractType: "Project",
    workModel: "Recruitment",
    languageRequirement: "English",
    salary: "NOK 290 - 330/hour",
    summary: "Join a structured project team delivering modern commercial installations in Oslo.",
    description:
      "We are recruiting experienced industrial electricians for a long-term rotation project in Oslo with clear planning and safety routines.",
    responsibilities: [
      "Install and maintain low-voltage systems based on project plans.",
      "Coordinate work with site supervisors and report daily progress.",
    ],
    requirements: [
      "Minimum 3 years electrical experience in construction or industry.",
      "Relevant documentation and strong safety awareness.",
    ],
    benefits: ["Accommodation support", "Structured onboarding", "Stable rotation planning"],
    startDate: "2026-05-15",
    applicationMethod: "internal",
    status: "active",
    featured: true,
    publishedAt: "2026-04-18",
    applicationCount: 17,
    syncStatus: "none",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "manual-002",
    source: "manual",
    title: "Concrete Worker, Trondheim",
    slug: "concrete-worker-trondheim",
    companyName: "ArbeidMatch Client Partner",
    hideCompany: true,
    location: "Trondheim",
    category: "Construction",
    trade: "Concrete Worker",
    contractType: "Permanent",
    workModel: "Permanent",
    languageRequirement: "English",
    salary: "NOK 255 - 290/hour",
    summary: "Permanent role on modern residential and public infrastructure projects.",
    description:
      "An established construction team in Trondheim is expanding and hiring concrete workers focused on quality and teamwork.",
    responsibilities: "Prepare formwork\nExecute casting and finishing\nFollow HSE procedures",
    requirements: "At least 2 years relevant experience\nBasic English communication",
    benefits: "Long-term contract\nProfessional recruitment support",
    applicationMethod: "internal",
    status: "draft",
    featured: false,
    publishedAt: null,
    syncStatus: "none",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "recman-001",
    source: "recman",
    externalId: "RM-78431",
    title: "TIG Welder, Bergen Shipyard",
    slug: "tig-welder-bergen-shipyard",
    companyName: "Fjord Marine Services",
    hideCompany: false,
    location: "Bergen",
    category: "Welding",
    trade: "TIG Welder",
    contractType: "Temporary",
    workModel: "Bemanning",
    languageRequirement: "English",
    salary: "From NOK 320/hour",
    summary: "Precision TIG welding for marine upgrades with structured quality control.",
    description: "Experienced TIG welders needed for shipyard retrofit and maintenance operations in Bergen.",
    responsibilities: ["Perform TIG welding on stainless and duplex materials", "Follow WPS and QA checks"],
    requirements: ["Marine or offshore TIG experience", "Technical drawing reading skills"],
    benefits: ["Predictable schedule", "Long-term client pipeline"],
    applicationMethod: "external_url",
    applicationUrl: "https://apply.recman.no/arbeidmatch/jobs/78431",
    status: "active",
    featured: true,
    publishedAt: "2026-04-16",
    syncStatus: "synced",
    lastSyncedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "recman-002",
    source: "recman",
    externalId: "RM-78477",
    title: "Truck Driver C-Class, Stavanger",
    slug: "truck-driver-c-class-stavanger",
    companyName: null,
    hideCompany: true,
    location: "Stavanger",
    category: "Transport",
    trade: "Truck Driver",
    contractType: "Temporary",
    workModel: "Bemanning",
    languageRequirement: "Norwegian",
    summary: "Regional distribution role with modern fleet and predictable routes.",
    description: "Reliable C-class drivers needed for regional logistics routes in Stavanger.",
    responsibilities: "Daily route deliveries\nVehicle checks",
    requirements: "Valid C-class licence\nDriver card",
    applicationMethod: "email",
    applicationEmail: "post@arbeidmatch.no",
    status: "active",
    featured: false,
    publishedAt: "2026-04-12",
    syncStatus: "pending",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "recman-003",
    source: "recman",
    externalId: "RM-70001",
    title: "HVAC Technician, Drammen Service Team",
    slug: "hvac-technician-drammen-service",
    location: "Drammen",
    category: "Mechanical",
    trade: "HVAC Technician",
    contractType: "Temporary",
    workModel: "Recruitment",
    description: "Role closed after successful placement.",
    applicationMethod: "external_url",
    applicationUrl: "https://apply.recman.no/arbeidmatch/jobs/70001",
    status: "closed",
    syncStatus: "synced",
    publishedAt: "2026-03-20",
    expiryDate: "2026-04-10",
    createdAt: now,
    updatedAt: now,
  },
];
