import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const out = new URL('../.recos-verification/', import.meta.url);
await mkdir(out, { recursive: true });
const base = process.env.RECOS_BASE_URL || 'http://127.0.0.1:4175';
const checks = [], errors = [], writes = [], remote = [];
const ok = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log('PASS', name); };
const browser = await chromium.launch({ args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.on('pageerror', e => errors.push(e.message));
page.on('request', r => { if (r.method() !== 'GET') writes.push(r.url()); if (!r.url().startsWith(base + '/') && !r.url().startsWith('data:')) remote.push(r.url()); });
const shot = name => page.screenshot({ path: fileURLToPath(new URL(name + '.png', out)) });
const choose = async view => { await page.locator(`[data-product="${view}"]`).click(); await page.waitForFunction(v => document.querySelector('canvas').dataset.view === v, view); };
try {
 await page.goto(base + '/recos#arrival');
 await page.waitForFunction(() => document.body.dataset.scene === 'ready');
 ok('Starts with one recruiter seat', await page.locator('#seat-output').textContent() === '1');
 ok('Fifteen fictional screenshots are ready in the 3D scene', await page.locator('canvas').getAttribute('data-screens') === '15');
 const before = await page.locator('canvas').screenshot();
 for (const view of ['overview', 'candidates', 'clients', 'presentations', 'pipeline', 'assistant', 'team']) {
  await choose(view);
  ok('Product tab selects ' + view, await page.locator(`[data-product="${view}"]`).getAttribute('aria-pressed') === 'true');
 }
 ok('Changing options changes the rendered screen', !before.equals(await page.locator('canvas').screenshot()));
 await choose('candidates'); await page.locator('#open-product').click();
 const demo = page.frameLocator('#product-frame');
 await demo.locator('body[data-view="candidates"]').waitFor();
 ok('Preview clearly identifies fictional data', (await demo.locator('.demo-banner').innerText()).includes('fictional'));
 ok('Eight fictional candidate rows', await demo.locator('#candidate-rows tr').count() === 8);
 await demo.getByLabel('Search demo candidates').fill('welder');
 ok('Candidate search filters the demonstration', await demo.locator('#candidate-rows tr').count() === 1 && (await demo.locator('#candidate-rows').innerText()).includes('Welder TIG'));
 await demo.locator('[data-profile="2"]').click();
 ok('Candidate profile opens with matching trade', await demo.locator('#candidate-detail').isVisible() && (await demo.locator('#profile-content').innerText()).includes('Welder TIG'));
 await demo.getByRole('button', { name: 'Close candidate preview' }).click();
 await demo.getByLabel('Search demo candidates').fill('');
 await demo.locator('#available-filter').click();
 ok('Availability filter works', await demo.locator('#candidate-rows tr').count() === 3);
 await demo.locator('nav [data-view="pipeline"]').click();
 await demo.locator('[data-move="1"]').click();
 ok('Pipeline moves an example application', (await demo.locator('#demo-feedback').innerText()).includes('Candidate 01 moved to Screening'));
 ok('Parent screen follows preview navigation', await page.locator('[data-product="pipeline"]').getAttribute('aria-pressed') === 'true');
 await shot('desktop-interactive-pipeline');
 await demo.locator('[data-view="messages"]').first().click(); await demo.locator('[data-thread="1"]').click();
 ok('Message options switch the displayed conversation', await demo.locator('.conversation h2').innerText() === 'Example client');
 await demo.locator('nav [data-view="team"]').click(); await demo.locator('#add-demo-seat').click();
 await page.waitForFunction(() => document.querySelector('#seat-output').textContent === '2');
 ok('Demo team configuration updates the landing page', (await demo.locator('.team-summary').innerText()).startsWith('2 recruiter seats'));
 await page.getByRole('button', { name: 'Close product preview' }).click();
 ok('Closing returns to the selected 3D option', await page.locator('[data-product="team"]').getAttribute('aria-pressed') === 'true');
 await page.evaluate(() => window.postMessage({ type: 'recos-preview', view: 'messages', seats: 8 }, location.origin));
 ok('Messages from outside the preview frame are ignored', await page.locator('#seat-output').textContent() === '2');
 await page.locator('.chapter-rail [data-go="2"]').click();
 for (let i = 0; i < 6; i++) await page.locator('#add-seat').click();
 await page.waitForFunction(() => document.querySelector('canvas').dataset.seats === '8');
 ok('Team scene supports eight seats', await page.locator('#add-seat').isDisabled());
 await shot('desktop-team-eight');
 await page.locator('#open-product').click(); await demo.locator('body[data-view="team"][data-seats="8"]').waitFor();
 ok('Eight seats are reflected in the actual preview', await demo.locator('.member').count() === 8);
 await page.keyboard.press('Escape');
 await page.locator('#product-dialog').waitFor({ state: 'hidden' });
 for (const [width, height] of [[1440, 900], [1024, 768], [768, 1024], [390, 844], [390, 667], [320, 568]]) {
  await page.setViewportSize({ width, height });
  for (let chapter = 0; chapter < 5; chapter++) {
   await page.locator(`.chapter-rail [data-go="${chapter}"]`).click();
   await page.waitForFunction(i => Number(document.querySelector('canvas').dataset.progress) === i, chapter);
   ok(width + ' chapter ' + chapter + ': screen uses the expected side', await page.locator('canvas').getAttribute('data-side') === (width < 901 || chapter === 0 || chapter === 4 ? 'center' : chapter % 2 ? 'left' : 'right'));
   ok(`${width} chapter ${chapter}: no duplicate windows`, JSON.parse(await page.locator('canvas').getAttribute('data-screen-bounds')).length === (chapter === 4 ? 0 : 1));
   const copy = await page.locator('.chapter.active .chapter-copy').boundingBox(), controls = await page.locator('.product-controls').boundingBox(), rail = await page.locator('.chapter-rail').boundingBox();
   const header = await page.locator('body > header').boundingBox();
   ok(`${width}x${height} chapter ${chapter}: copy clears header`, copy.y >= header.y + header.height + 4);
   if (chapter === 4) ok(`${width}x${height}: final invitation is clear`, !controls && copy.y + copy.height < rail.y);
   else ok(`${width}x${height} chapter ${chapter}: options fit`, controls.x >= 0 && controls.x + controls.width <= width + 1 && controls.y + controls.height < rail.y && (width > 900 || copy.y + copy.height < controls.y));
   ok(`${width}x${height} chapter ${chapter}: no horizontal overflow`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
   await shot(`${width}x${height}-${chapter}`);
  }
 }
 await page.locator('.chapter-rail [data-go="3"]').click();
 await page.locator('#open-product').click(); await demo.locator('body[data-view]').waitFor();
 await demo.locator('nav [data-view="candidates"]').click();
 ok('Phone preview keeps all product navigation accessible', await demo.locator('nav button').count() === 7);
 await demo.getByLabel('Search demo candidates').fill('carpenter'); await demo.locator('[data-profile="1"]').first().click();
 ok('Phone candidate profile is usable', await demo.locator('#candidate-detail').isVisible());
 await shot('phone-candidate-profile'); await demo.getByRole('button', { name: 'Close candidate preview' }).click();
 await page.getByRole('button', { name: 'Close product preview' }).click();
 const fallback = await context.newPage(); await fallback.route('**/assets/recos-overview.png', r => r.abort());
 await fallback.goto(base + '/recos'); await fallback.waitForFunction(() => document.body.dataset.scene === 'fallback');
 await fallback.locator('[data-product="candidates"]').click(); await fallback.locator('#open-product').click();
 await fallback.frameLocator('#product-frame').locator('body[data-view="candidates"]').waitFor();
 ok('Missing 3D assets retain the interactive product preview', await fallback.locator('#product-dialog').isVisible()); await fallback.close();
 ok('No runtime errors', errors.length === 0);
 ok('No forms or messages sent', writes.length === 0);
 ok('All preview assets and fonts stay local', remote.length === 0);
 const response = await context.request.get(base + '/recos');
 ok('Public URL serves the full document', response.status() === 200 && (await response.text()).includes('BETA FULL - WAITLIST OPEN'));
 ok('Parent permits the same-origin demonstration', response.headers()['content-security-policy'].includes("frame-src 'self'"));
 ok('Landing remains protected against external framing', response.headers()['x-frame-options'] === 'DENY');
 const preview = await context.request.get(base + '/recos-experience/product-preview.html');
 ok('Only the fictional demo permits same-origin framing', preview.headers()['x-frame-options'] === 'SAMEORIGIN' && preview.headers()['content-security-policy'].includes("frame-ancestors 'self'"));
 await page.locator('.chapter-rail [data-go="3"]').click();
 await choose('clients'); await page.locator('#open-product').click();
 await demo.locator('[data-client="0"]').click();
 ok('Client relationship explains the next step', (await demo.locator('#profile-content').innerText()).includes('Discuss requirements'));
 await demo.locator('#close-profile').click(); await demo.locator('nav [data-view="presentations"]').click();
 await demo.locator('[data-presentation]').first().click();
 ok('Client presentation opens a fictional shortlist', (await demo.locator('#profile-content').innerText()).includes('A focused shortlist'));
 await demo.locator('#close-profile').click(); await demo.locator('nav [data-view="assistant"]').click();
 await demo.locator('[data-assist="followup"]').click();
 ok('Assistant demonstrates a reviewable draft', (await demo.locator('#assistant-answer').innerText()).includes('You review the wording'));
 await demo.locator('[data-support]').click();
 ok('AI and human support availability is explicit', (await demo.locator('#assistant-answer').innerText()).includes('24/7'));
 await page.getByRole('button', { name: 'Close product preview' }).click();
 await page.locator('.chapter-rail [data-go="4"]').click();
 ok('Final chapter has one clear signup action', await page.locator('.chapter.active [data-interest]').count() === 1);
 ok('Final action explicitly requests a beta slot', (await page.locator('.chapter.active [data-interest]').innerText()).includes('Request a beta slot'));
 await page.locator('.chapter.active [data-interest]').click();
 ok('Final action opens the waitlist signup', await page.locator('#interest-dialog').isVisible());
 await page.getByRole('button', { name: 'Close beta signup' }).click();
 let payload, mode = 'error';
 await page.route('**/api/feature-waitlist', async route => {
  payload = route.request().postDataJSON();
  await route.fulfill({ status: mode === 'error' ? 503 : 200, contentType: 'application/json', body: JSON.stringify(mode === 'error' ? { error: 'unavailable' } : { success: true }) });
 });
 await page.locator('.header-cta').click();
 ok('Beta dialog explains slots are full', (await page.locator('#interest-dialog').innerText()).includes('Beta slots are currently full'));
 await page.locator('[name="email"]').fill('recos-test@example.invalid');
 await page.locator('#interest-form [type="submit"]').click();
 ok('Consent is required before submission', !payload);
 await page.locator('[name="consent"]').check();
 await page.locator('#interest-form [type="submit"]').click();
 await page.waitForFunction(() => document.querySelector('#form-result').textContent.includes('could not confirm'));
 ok('Failure keeps the form available for retry', await page.locator('#interest-form').isVisible());
 ok('Failure retains the email', await page.locator('[name="email"]').inputValue() === 'recos-test@example.invalid');
 mode = 'success';
 await page.locator('#interest-type').selectOption('team');
 await page.locator('#interest-form [type="submit"]').click();
 await page.waitForFunction(() => document.querySelector('#form-result').textContent.includes("You're on the list"));
 ok('Success is shown only after the server accepts signup', !(await page.locator('#interest-form').isVisible()));
 ok('Signup records RecOS consent and team interest', payload.feature === 'RecOS Beta' && payload.consent === true && payload.wants_assistance.includes('interest=team'));
 ok('No account or slot reservation is claimed', (await page.locator('#form-result').innerText()).includes('Current beta slots are full'));
 await shot('phone-waitlist-success');
 await page.getByRole('button', { name: 'Close beta signup' }).click();
 for (const width of [1440, 390]) {
  await page.setViewportSize({width, height: width === 390 ? 844 : 900});
  await page.locator('.chapter-rail [data-go="0"]').click();
  await shot(width + '-beta-arrival');
  await page.locator('.header-cta').click();
  await shot(width + '-beta-signup');
  await page.getByRole('button', { name: 'Close beta signup' }).click();
 }
 ok('No new JavaScript errors during signup', errors.length === 0);
 await writeFile(new URL('verification.json', out), JSON.stringify({ passed: checks.length, checks, errors, writes, remote }, null, 2));
 console.log(checks.length + ' product checks passed.');
} finally { await browser.close(); }
