/**
 * THE REQUEST WIZARD'S WORDS, IN ENGLISH AND IN NORWEGIAN (bokmål).
 *
 * The owner, 28 September 2026: a client who opens the wizard from a company
 * presentation we sent reads it in Norwegian. Everyone who comes from the site
 * keeps the English wizard, word for word as it was.
 *
 * Only what the client reads changes. The values the wizard stores and sends
 * (option keys, "Yes"/"No", "Immediate", the notes text, the role detail lines)
 * stay in English, because the ATS parses them: a Norwegian label here is a
 * display of an English value, never a replacement for it.
 *
 * No en or em dash anywhere in this file: the repository check rejects them.
 */
import { positionNb } from "@/lib/request-position-nb";

export type RequestLang = "en" | "no";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Norwegian for a client who came from a presentation: a live presentation
 * ticket (the server's answer), or the presentation marks on the address (the
 * deck id, or source=presentation), which show the right language while the
 * ticket is still loading. The language never grants anything: access is the
 * token gate's alone.
 */
export function requestLangFrom(opts: { presentationTicket: boolean; source: string | null; deck: string | null }): RequestLang {
  if (opts.presentationTicket) return "no";
  if ((opts.source ?? "").trim() === "presentation") return "no";
  if (UUID.test((opts.deck ?? "").trim())) return "no";
  return "en";
}

/** "{name}" placeholders filled in. */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) => (key in vars ? String(vars[key]) : whole));
}

const en = {
  // Gate screens
  loading: "Loading…",
  blockedMessage: "Please complete the initial request form first.",
  blockedLink: "Go to request form",
  errorMessage: "We could not load this request link.",
  errorLink: "Start from the request form",

  // Thank-you screen
  thankYouNamed: "Thank you, {name}!",
  thankYou: "Thank you!",
  detailedOfferNote:
    "Thank you for your request. We will confirm by email as soon as possible whether we can take it on.",
  yourReference: "Your reference: {ref}",
  respondTime: "We typically respond within 1-2 business days.",
  backHome: "Back to homepage",
  submitNoticeEmail: "Request saved, but we could not send the confirmation email right now.",
  submitError: "Could not submit request. Please try again.",

  // Shared
  stepOf: "Step {n} of {total}",
  fieldRequired: "This field is required",
  optional: "(optional)",
  back: "← Back",
  submitting: "Submitting...",
  submit: "Submit",
  continue: "Continue →",
  privacyFooter: "We use your contact details to answer this request and to prepare an offer.",
  privacyFooterLink: "Read our privacy policy",

  // Step 0: company and contact
  step0Title: "Company and contact",
  phCompanyName: "Your company name",
  phOrgNumber: "Norwegian org. number",
  phFirstName: "First name",
  phLastName: "Last name",
  phRoleInCompany: "Your role in the company (e.g. Owner, HR manager)",
  ariaPhoneCountryCode: "Phone country code",
  phPhone: "+47 000 00 000",
  phEmail: "work@yourcompany.no",
  privacyConfirmBefore:
    "I confirm that I am authorised to send this request on behalf of my company, and that I have read the",
  privacyNoticeLink: "privacy notice",
  privacyError: "Please confirm that you have read the privacy notice to continue",
  termsBefore: "I accept the",
  termsLink: "terms and conditions",
  termsError: "Please accept the terms and conditions to continue",
  howDidYouHear: "How did you hear about us",
  phReferralCompany: "Company name",
  phReferralEmail: "Company email (optional)",
  referralEmailError: "Enter a valid email or leave blank",

  // Step 1: job basics
  step1Title: "Job basics",
  requesterKindQuestion: "What kind of business are you?",
  requesterKindError: "Please tell us what kind of business you are.",
  kindOwnLabel: "We need people for our own work",
  kindOwnHelp: "The people will work on our own projects.",
  kindAgencyLabel: "We are a staffing or recruitment agency",
  kindAgencyHelp: "We supply people on to our own clients.",
  serviceQuestion: "Which service do you need?",
  serviceError: "Please choose a service.",
  serviceStaffingLabel: "Staffing (bemanning)",
  serviceStaffingHelp: "We hire out skilled workers who are employed by us.",
  serviceRecruitmentLabel: "Recruitment",
  serviceRecruitmentHelp: "We run the whole process up to the hire at your company.",
  serviceSourcingLabel: "Sourcing",
  serviceSourcingHelp: "We find and sort the candidates, you hire them yourselves.",
  serviceAdvertisingLabel: "Job advertising",
  serviceAdvertisingHelp: "Coming soon",
  advertTitle: "Job adverts have their own form",
  advertBody1: "There you write the full advert, we check it before it is published, and you choose the package that suits you.",
  advertBody2: "The details you have already given us come along, so you do not type them twice.",
  advertLink: "Write your job advert",
  advertAlt: "Looking for staffing or recruitment instead? Choose it above.",
  jobCategory: "Job category",
  jobSummary: "Job summary",
  tradeOrPosition: "Trade or position",
  phCustomPosition: "Enter custom position...",
  phPositionNoIndustry: "Select industry first or enter position",
  requiredSkills: "Required skills (optional)",
  requiredSkillsHelp: "Select the skills most important for this position.",
  location: "Location",
  phLocation: "Search or type a place",
  removePlace: "Remove {place}",
  addPlace: 'Add "{place}"',
  numberOfWorkers: "Number of workers",
  contractType: "Contract type",
  startDate: "Start date",
  worksiteAddress: "Worksite address",
  phStreet: "Street and number",
  ariaStreet: "Worksite street and number",
  phPostcode: "Postcode",
  ariaPostcode: "Worksite postcode",
  postcodeError: "4 digits",
  phCityExample: "e.g. {city}",
  phCity: "City",
  ariaCity: "Worksite city",
  assignmentPeriod: "How long do you need the people? (assignment period)",
  from: "From",
  to: "To",
  ariaFrom: "Assignment from",
  ariaTo: "Assignment to",
  periodToError: "Choose an end date on or after the start.",

  // Step 2: salary and conditions
  step2Title: "Salary and conditions",
  salaryMode: "Salary mode",
  salaryPeriod: "Salary period",
  perHour: "Per hour",
  perMonth: "Per month",
  salaryPerHourNok: "Salary (per hour, NOK)",
  minWagesLink: "View minimum wages →",
  phSalaryMin: "e.g. 220 NOK/hour",
  phSalaryMax: "To (NOK/hour)",
  minWageNote: "Must meet Arbeidstilsynet minimum wage requirements",
  accommodation: "Accommodation",
  accommodationCost: "Accommodation cost",
  phAccommodationCost: "e.g. 5000 NOK or describe",
  localTravel: "Local travel",
  internationalTravelCosts: "International travel costs",
  intlCovered: "Covered by company",
  intlOwn: "Candidate's own responsibility",
  rotation: "Rotation",
  ariaRotation: "Rotation or work schedule",
  assignmentTitle: "The assignment",
  assignmentHelp: "Where and when our workers will be with you, and who leads them on site.",
  hoursPerWeek: "Hours per week",
  phHours: "e.g. 37.5",
  hoursError: "Enter the hours per week (1 to 80).",
  shiftPattern: "Shift pattern",
  approverQuestion: "Who approves the hours on site",
  phName: "Name",
  phPhoneShort: "Phone",
  approverPhoneError: "Enter a phone number.",
  ppeQuestion: "Do you provide the protective equipment?",
  ariaPpe: "Protective equipment provided by you",
  hiringProcessTitle: "The hiring process",
  hiringProcessHelp: "How you will choose the candidate and when you need them.",
  probation: "Probation period",
  interviewRounds: "Interview rounds",
  interviewer: "Who interviews the candidate",
  phInterviewer: "e.g. the site manager and HR",
  hireBy: "Hire needed by",
  subscribeLabel: "I want emails from ArbeidMatch when candidates matching this request become available.",
  subscribeHelp:
    "Optional. Presentations are sent when suitable candidates are available, not immediately after your request. To stop updates, contact",
  subscribeHelpSupport: "our support",

  // Step 3: requirements
  step3Title: "Requirements",
  qualification: "Qualification",
  dNumberHas: "Already has a D-number",
  dNumberWeHandle: "We can handle the procedure",
  drivingLicense: "Driving license",
  tradeCertPreferred: "Trade certificate preferred",
  customerCommRequired: "Customer communication required",
  languageAtWork: "Language at work",
  norwegianNeeded: "Norwegian needed at work",
  whyNorwegian: "Why does the work need Norwegian?",
  phWhyNorwegian: "e.g. daily contact with customers, safety briefings in Norwegian",
  whyNorwegianHelp: "Candidates who speak Norwegian well are fewer, so it helps us to know what the language is used for.",
  whyNorwegianError: "Tell us in a few words what the language is needed for.",
  englishNeeded: "English needed at work",
  teamNationalities: "Nationalities on the team today",
  phTeamNationalities: "e.g. Norwegian, Polish, Lithuanian",
  teamNationalitiesHelp: "It helps us pick candidates who come into the crew from day one.",
  teamLanguage: "Language spoken within the team",
  phTeamLanguage: "e.g. Norwegian on site, English within the crew",
  aboutRole: "About the {role} role",

  // Step 4: work tasks
  step4Title: "Work tasks",
  workTasksIntro: "What will the {worker} do day to day? One task per line.",
  workerFallback: "worker",
  workerWithRole: "{role}",
  ariaWorkTasks: "Work tasks",
  workTasksError: "Please describe the work tasks (at least a few words).",

  // Steps 5 to 8
  step5Title: "Personal qualities",
  step6Title: "We offer",
  step7Title: "Review your request",
  reviewIntroPresentation: "Check the summary below and send it.",
  reviewIntro: "Check the summary below. You can add optional notes on the next step.",
  reviewConditionsSeparate: "We agree pay and working conditions with you separately.",
  addMoreDetails: "Add more details",
  additionalNotes: "Additional notes",
  additionalNotesOptional: "Additional notes (optional)",

  // The review's rows
  rowCompany: "Company",
  rowContact: "Contact",
  rowBusiness: "Business",
  rowService: "Service",
  rowJobCategory: "Job category",
  rowPosition: "Position",
  rowLocation: "Location",
  rowWorkers: "Number of workers",
  rowEmploymentType: "Employment type",
  rowStart: "Start",
  rowSalaryHour: "Salary (NOK/hour)",
  rowSalaryMonth: "Salary (NOK/month)",
  rowAccommodation: "Accommodation",
  rowLocalTravel: "Local travel",
  rowInternationalTravel: "International travel",
  businessAgency: "Staffing or recruitment agency",
  businessOwn: "Hiring for our own work",

  // The review's summary block (shown in Norwegian; the stored notes stay English)
  notesAboutPosition: "About the Position",
  notesWorkTasks: "Work Tasks",
  notesRequirements: "Requirements",
  notesQualification: "Qualification",
  notesDriverLicense: "Driver license",
  notesNotSpecified: "Not specified",
  notesTradeCertPreferred: "Trade certificate preferred",
  notesCustomerComm: "Customer communication required",
  notesPersonalQualities: "Personal Qualities",
  notesWeOffer: "We Offer",
  notesAdditional: "Additional Notes",
  notesRoleDetails: "Role details",
  periodFromTo: "{from} to {to}",
  periodFromOpen: "From {from}, open-ended",
  periodFromOnly: "From {from}",
};

export type WordKey = keyof typeof en;

const no: Record<WordKey, string> = {
  loading: "Laster…",
  blockedMessage: "Fyll ut det første forespørselsskjemaet først.",
  blockedLink: "Gå til forespørselsskjemaet",
  errorMessage: "Vi kunne ikke åpne denne lenken til forespørselen.",
  errorLink: "Start fra forespørselsskjemaet",

  thankYouNamed: "Takk, {name}!",
  thankYou: "Takk!",
  detailedOfferNote:
    "Takk for forespørselen. Vi bekrefter på e-post så snart som mulig om vi kan ta oss av den.",
  yourReference: "Deres referanse: {ref}",
  respondTime: "Vi svarer vanligvis innen 1-2 virkedager.",
  backHome: "Tilbake til forsiden",
  submitNoticeEmail: "Forespørselen er lagret, men vi kunne ikke sende bekreftelsen på e-post akkurat nå.",
  submitError: "Vi kunne ikke sende forespørselen. Prøv igjen.",

  stepOf: "Steg {n} av {total}",
  fieldRequired: "Dette feltet må fylles ut",
  optional: "(valgfritt)",
  back: "← Tilbake",
  submitting: "Sender...",
  submit: "Send forespørsel",
  continue: "Fortsett →",
  privacyFooter: "Vi bruker kontaktopplysningene deres til å besvare denne forespørselen og utarbeide et tilbud.",
  privacyFooterLink: "Les personvernerklæringen vår",

  step0Title: "Bedrift og kontaktperson",
  phCompanyName: "Bedriftens navn",
  phOrgNumber: "Organisasjonsnummer",
  phFirstName: "Fornavn",
  phLastName: "Etternavn",
  phRoleInCompany: "Din rolle i bedriften (f.eks. daglig leder, HR-sjef)",
  ariaPhoneCountryCode: "Landkode for telefon",
  phPhone: "+47 000 00 000",
  phEmail: "navn@bedrift.no",
  privacyConfirmBefore:
    "Jeg bekrefter at jeg har fullmakt til å sende denne forespørselen på vegne av bedriften, og at jeg har lest",
  privacyNoticeLink: "personvernerklæringen",
  privacyError: "Bekreft at du har lest personvernerklæringen for å gå videre",
  termsBefore: "Jeg godtar",
  termsLink: "vilkårene",
  termsError: "Du må godta vilkårene for å gå videre",
  howDidYouHear: "Hvordan hørte dere om oss",
  phReferralCompany: "Bedriftens navn",
  phReferralEmail: "Bedriftens e-post (valgfritt)",
  referralEmailError: "Skriv inn en gyldig e-postadresse, eller la feltet stå tomt",

  step1Title: "Om behovet",
  requesterKindQuestion: "Hva slags virksomhet er dere?",
  requesterKindError: "Fortell oss hva slags virksomhet dere er.",
  kindOwnLabel: "Vi trenger folk til egen drift",
  kindOwnHelp: "Folkene skal jobbe i våre egne prosjekter.",
  kindAgencyLabel: "Vi er et bemannings- eller rekrutteringsbyrå",
  kindAgencyHelp: "Vi leverer folk videre til våre egne kunder.",
  serviceQuestion: "Hvilken tjeneste trenger dere?",
  serviceError: "Velg en tjeneste.",
  serviceStaffingLabel: "Bemanning",
  serviceStaffingHelp: "Vi leier ut fagfolk som er ansatt hos oss.",
  serviceRecruitmentLabel: "Rekruttering",
  serviceRecruitmentHelp: "Vi tar hele prosessen frem til ansettelse hos dere.",
  serviceSourcingLabel: "Sourcing",
  serviceSourcingHelp: "Vi finner og sorterer kandidatene, dere ansetter selv.",
  serviceAdvertisingLabel: "Stillingsannonser",
  serviceAdvertisingHelp: "Kommer snart",
  advertTitle: "Stillingsannonser har et eget skjema",
  advertBody1: "Der skriver dere hele annonsen, vi kontrollerer den før den publiseres, og dere velger pakken som passer.",
  advertBody2: "Opplysningene dere allerede har gitt oss blir med, så dere slipper å skrive dem på nytt.",
  advertLink: "Skriv stillingsannonsen",
  advertAlt: "Ser dere heller etter bemanning eller rekruttering? Velg det ovenfor.",
  jobCategory: "Fagområde",
  jobSummary: "Kort om behovet",
  tradeOrPosition: "Fag eller stilling",
  phCustomPosition: "Skriv inn stilling...",
  phPositionNoIndustry: "Velg fagområde først, eller skriv inn stilling",
  requiredSkills: "Ønskede ferdigheter (valgfritt)",
  requiredSkillsHelp: "Velg ferdighetene som er viktigst for stillingen.",
  location: "Arbeidssted",
  phLocation: "Søk etter eller skriv inn et sted",
  removePlace: "Fjern {place}",
  addPlace: 'Legg til "{place}"',
  numberOfWorkers: "Antall personer",
  contractType: "Ansettelsesform",
  startDate: "Oppstart",
  worksiteAddress: "Adresse til arbeidsstedet",
  phStreet: "Gate og husnummer",
  ariaStreet: "Arbeidsstedets gate og husnummer",
  phPostcode: "Postnr.",
  ariaPostcode: "Arbeidsstedets postnummer",
  postcodeError: "4 siffer",
  phCityExample: "f.eks. {city}",
  phCity: "Poststed",
  ariaCity: "Arbeidsstedets poststed",
  assignmentPeriod: "Hvor lenge trenger dere folkene? (oppdragsperiode)",
  from: "Fra",
  to: "Til",
  ariaFrom: "Oppdraget starter",
  ariaTo: "Oppdraget slutter",
  periodToError: "Velg en sluttdato som er samme dag som eller etter startdatoen.",

  step2Title: "Lønn og betingelser",
  salaryMode: "Lønnsform",
  salaryPeriod: "Lønnsperiode",
  perHour: "Per time",
  perMonth: "Per måned",
  salaryPerHourNok: "Lønn (per time, NOK)",
  minWagesLink: "Se minstelønnssatser →",
  phSalaryMin: "f.eks. 220 NOK/time",
  phSalaryMax: "Til (NOK/time)",
  minWageNote: "Må oppfylle kravene til minstelønn fra Arbeidstilsynet",
  accommodation: "Bolig",
  accommodationCost: "Kostnad for bolig",
  phAccommodationCost: "f.eks. 5000 NOK, eller beskriv",
  localTravel: "Lokal reise",
  internationalTravelCosts: "Reisekostnader fra utlandet",
  intlCovered: "Dekkes av bedriften",
  intlOwn: "Kandidatens eget ansvar",
  rotation: "Rotasjon",
  ariaRotation: "Rotasjon eller arbeidsplan",
  assignmentTitle: "Oppdraget",
  assignmentHelp: "Hvor og når våre arbeidere skal være hos dere, og hvem som leder dem på stedet.",
  hoursPerWeek: "Timer per uke",
  phHours: "f.eks. 37,5",
  hoursError: "Skriv inn timer per uke (1 til 80).",
  shiftPattern: "Skiftordning",
  approverQuestion: "Hvem godkjenner timene på stedet",
  phName: "Navn",
  phPhoneShort: "Telefon",
  approverPhoneError: "Skriv inn et telefonnummer.",
  ppeQuestion: "Stiller dere verneutstyret?",
  ariaPpe: "Verneutstyr som dere stiller",
  hiringProcessTitle: "Ansettelsesprosessen",
  hiringProcessHelp: "Hvordan dere velger kandidaten, og når dere trenger vedkommende.",
  probation: "Prøvetid",
  interviewRounds: "Intervjurunder",
  interviewer: "Hvem intervjuer kandidaten",
  phInterviewer: "f.eks. anleggsleder og HR",
  hireBy: "Ansettelse innen",
  subscribeLabel: "Jeg ønsker e-post fra ArbeidMatch når kandidater som passer denne forespørselen blir tilgjengelige.",
  subscribeHelp:
    "Valgfritt. Presentasjoner sendes når passende kandidater er tilgjengelige, ikke rett etter forespørselen. For å stoppe oppdateringene, kontakt",
  subscribeHelpSupport: "vår support",

  step3Title: "Krav",
  qualification: "Erfaring",
  dNumberHas: "Har allerede D-nummer",
  dNumberWeHandle: "Vi kan håndtere prosedyren",
  drivingLicense: "Førerkort",
  tradeCertPreferred: "Fagbrev foretrekkes",
  customerCommRequired: "Kundekontakt påkrevd",
  languageAtWork: "Språk i arbeidet",
  norwegianNeeded: "Norsk som trengs i arbeidet",
  whyNorwegian: "Hvorfor trengs norsk i arbeidet?",
  phWhyNorwegian: "f.eks. daglig kundekontakt, sikkerhetsgjennomganger på norsk",
  whyNorwegianHelp: "Det er færre kandidater som snakker godt norsk, så det hjelper oss å vite hva språket brukes til.",
  whyNorwegianError: "Fortell oss med noen få ord hva språket trengs til.",
  englishNeeded: "Engelsk som trengs i arbeidet",
  teamNationalities: "Nasjonaliteter i arbeidslaget i dag",
  phTeamNationalities: "f.eks. norsk, polsk, litauisk",
  teamNationalitiesHelp: "Det hjelper oss å velge kandidater som finner seg til rette i arbeidslaget fra første dag.",
  teamLanguage: "Språk som snakkes i arbeidslaget",
  phTeamLanguage: "f.eks. norsk på byggeplassen, engelsk i arbeidslaget",
  aboutRole: "Om stillingen som {role}",

  step4Title: "Arbeidsoppgaver",
  workTasksIntro: "Hvilke arbeidsoppgaver skal {worker} ha til daglig? Én oppgave per linje.",
  workerFallback: "den ansatte",
  workerWithRole: "en {role}",
  ariaWorkTasks: "Arbeidsoppgaver",
  workTasksError: "Beskriv arbeidsoppgavene (minst noen få ord).",

  step5Title: "Personlige egenskaper",
  step6Title: "Vi tilbyr",
  step7Title: "Se over forespørselen",
  reviewIntroPresentation: "Se over sammendraget nedenfor og send det.",
  reviewIntro: "Se over sammendraget nedenfor. Dere kan legge til valgfrie merknader i neste steg.",
  reviewConditionsSeparate: "Lønn og arbeidsvilkår avtaler vi med dere separat.",
  addMoreDetails: "Legg til flere detaljer",
  additionalNotes: "Tilleggsinformasjon",
  additionalNotesOptional: "Tilleggsinformasjon (valgfritt)",

  rowCompany: "Bedrift",
  rowContact: "Kontaktperson",
  rowBusiness: "Virksomhet",
  rowService: "Tjeneste",
  rowJobCategory: "Fagområde",
  rowPosition: "Stilling",
  rowLocation: "Arbeidssted",
  rowWorkers: "Antall personer",
  rowEmploymentType: "Ansettelsesform",
  rowStart: "Oppstart",
  rowSalaryHour: "Lønn (NOK/time)",
  rowSalaryMonth: "Lønn (NOK/måned)",
  rowAccommodation: "Bolig",
  rowLocalTravel: "Lokal reise",
  rowInternationalTravel: "Reise fra utlandet",
  businessAgency: "Bemannings- eller rekrutteringsbyrå",
  businessOwn: "Ansetter til egen drift",

  notesAboutPosition: "Om stillingen",
  notesWorkTasks: "Arbeidsoppgaver",
  notesRequirements: "Krav",
  notesQualification: "Erfaring",
  notesDriverLicense: "Førerkort",
  notesNotSpecified: "Ikke oppgitt",
  notesTradeCertPreferred: "Fagbrev foretrekkes",
  notesCustomerComm: "Kundekontakt påkrevd",
  notesPersonalQualities: "Personlige egenskaper",
  notesWeOffer: "Vi tilbyr",
  notesAdditional: "Tilleggsinformasjon",
  notesRoleDetails: "Detaljer om stillingen",
  periodFromTo: "{from} til {to}",
  periodFromOpen: "Fra {from}, uten sluttdato",
  periodFromOnly: "Fra {from}",
};

export const REQUEST_WORDS: Record<RequestLang, Record<WordKey, string>> = { en, no };

// ---------------------------------------------------------------------------
// The options: the value stays English, the label the client reads is here.
// ---------------------------------------------------------------------------

const ROTATION_NB: Record<string, string> = {
  "No rotation / Standard schedule": "Ingen rotasjon / vanlig arbeidstid",
  "1 week on / 1 week off": "1 uke på / 1 uke av",
  ...Object.fromEntries(
    [2, 3, 4, 5, 6, 7, 8].map((n) => [`${n} weeks on / ${n} weeks off`, `${n} uker på / ${n} uker av`]),
  ),
};

/** Every option value the wizard shows as a button, card or chip, in Norwegian. */
export const OPTION_NB: Record<string, string> = {
  // Job categories
  Electrical: "Elektro",
  "Plumbing and HVAC (VVS)": "Rørlegger og VVS",
  Construction: "Bygg og anlegg",
  "Welding and Metal": "Sveis og metall",
  Logistics: "Logistikk",
  "Industry and Production": "Industri og produksjon",
  Cleaning: "Renhold",
  HoReCa: "Hotell, restaurant og catering",
  Healthcare: "Helse og omsorg",

  // Job summary
  "General hiring inquiry": "Generell forespørsel om arbeidskraft",
  "Urgent replacement need": "Akutt behov for erstatning",
  "Planned team expansion": "Planlagt utvidelse av arbeidslaget",
  "Project-specific hiring": "Behov knyttet til et bestemt prosjekt",

  // Contract type, start, salary
  "Permanent employment": "Fast ansettelse",
  "Temporary hire": "Midlertidig ansettelse",
  "Project-based": "Prosjektbasert",
  Immediate: "Snarest",
  "Specific start date": "Bestemt startdato",
  Range: "Lønnsspenn",
  Fixed: "Fast lønn",

  // Accommodation and travel
  "We help find accommodation": "Arbeidsgiver hjelper med å finne bolig",
  "Candidate finds own": "Kandidaten finner bolig selv",
  Covered: "Dekkes",
  "Not covered": "Dekkes ikke",

  // Requirements
  "No minimum": "Ingen minstekrav",
  "1 to 2 years": "1 til 2 år",
  "3 to 5 years": "3 til 5 år",
  "5+ years": "Over 5 år",
  "No driving license required": "Førerkort ikke påkrevd",
  Yes: "Ja",
  No: "Nei",
  "Not needed": "Ikke nødvendig",
  Basic: "Grunnleggende",
  "Good spoken": "Godt muntlig",
  Fluent: "Flytende",

  // Staffing and recruitment
  Day: "Dag",
  Evening: "Kveld",
  Night: "Natt",
  Rotation: "Rotasjon",
  None: "Ingen",
  "3 months": "3 måneder",
  "6 months": "6 måneder",

  // Personal qualities and what the client offers
  Accurate: "Nøyaktig",
  "Quality-conscious": "Kvalitetsbevisst",
  "Solution-oriented": "Løsningsorientert",
  Independent: "Selvstendig",
  "Team player": "Lagspiller",
  "Service-minded": "Serviceinnstilt",
  "Clear communicator": "Kommuniserer tydelig",
  "Competitive terms": "Konkurransedyktige betingelser",
  "Professional development": "Faglig utvikling",
  "Training opportunities": "Muligheter for opplæring",

  // How they heard about us
  "Referral from another company": "Anbefalt av en annen bedrift",
  "Google search": "Google-søk",
  LinkedIn: "LinkedIn",
  "Social media": "Sosiale medier",
  "Industry event or conference": "Bransjearrangement eller konferanse",
  Other: "Annet",

  // Trade question options (src/lib/request-role-questions.ts)
  Road: "Vei",
  Tunnel: "Tunnel",
  "Building site": "Byggeplass",
  Quarry: "Steinbrudd",
  "Pallet or stacker truck": "Palletruck eller stabler",
  "Reach truck": "Skyvemasttruck",
  "Counterbalance truck": "Motvektstruck",
  Installation: "Installasjon",
  Service: "Service",
  Industrial: "Industri",
  Automation: "Automasjon",
  "New build": "Nybygg",
  Industry: "Industri",
  "MIG/MAG": "MIG/MAG",
  TIG: "TIG",
  MMA: "MMA",
  "Carbon steel": "Karbonstål",
  "Stainless steel": "Rustfritt stål",
  Aluminium: "Aluminium",
  Food: "Næringsmidler",
  "Metal and mechanical": "Metall og mekanisk",
  Wood: "Tre",
  Plastics: "Plast",
  Packaging: "Emballasje",
  Offices: "Kontorer",
  "Industrial sites": "Industrianlegg",
  "Construction final cleaning": "Byggvask",
  Hotels: "Hotell",
  Windows: "Vinduer",
  Restaurant: "Restaurant",
  Hotel: "Hotell",
  Canteen: "Kantine",
  Catering: "Catering",
  "Bar or café": "Bar eller kafé",
  "Nursing home": "Sykehjem",
  "Home care": "Hjemmetjeneste",
  Hospital: "Sykehus",
  "Assisted living": "Omsorgsbolig",

  ...ROTATION_NB,
};

/** An option's label for the client. The value itself never changes. */
export function optionLabel(lang: RequestLang, value: string): string {
  if (lang === "en") return value;
  return OPTION_NB[value] ?? value;
}

/** A position's label: the Norwegian title the confirmation letter already uses. */
export function positionLabel(lang: RequestLang, value: string): string {
  if (lang === "en") return value;
  if (value === "Other") return OPTION_NB.Other;
  return positionNb(value);
}

/** The optional skill checkboxes (src/lib/role-skills.ts) the wizard's positions reach. */
export const SKILL_NB: Record<string, string> = {
  "Motor control and drives (VSD)": "Motorstyring og frekvensomformere (VSD)",
  "PLC wiring and connection": "PLS-kabling og tilkobling",
  "High voltage (over 1000V)": "Høyspenning (over 1000 V)",
  "Cable pulling and termination": "Kabeltrekking og terminering",
  "Panel building": "Tavlebygging",
  "Maintenance and fault finding": "Vedlikehold og feilsøking",
  "PLC programming (Siemens/Allen-Bradley)": "PLS-programmering (Siemens/Allen-Bradley)",
  "SCADA systems": "SCADA-systemer",
  "Instrumentation calibration": "Kalibrering av instrumentering",
  "Control panel design": "Konstruksjon av styretavler",
  "Process automation": "Prosessautomasjon",
  "Safety systems (SIL)": "Sikkerhetssystemer (SIL)",
  "Rooftop PV installation": "Solcelleanlegg på tak",
  "String inverter connection": "Tilkobling av strenginverter",
  "Battery storage systems": "Batterilagring",
  "Grid connection": "Nettilkobling",
  "Structural mounting": "Montering av bærekonstruksjon",
  "Performance testing": "Ytelsestesting",
  "Hot and cold water installation": "Installasjon av varmt og kaldt vann",
  "Drainage and sewage": "Drenering og avløp",
  "Underfloor heating": "Gulvvarme",
  "Bathroom installation": "Baderomsinstallasjon",
  "Gas installation": "Gassinstallasjon",
  "Heat pump connection": "Tilkobling av varmepumpe",
  "Ventilation duct installation": "Montering av ventilasjonskanaler",
  "Air handling units (AHU)": "Ventilasjonsaggregater (AHU)",
  "Balancing and commissioning": "Innregulering og igangkjøring",
  "Heat recovery systems": "Varmegjenvinning",
  "Refrigerant handling (F-gass)": "Håndtering av kuldemedier (F-gass)",
  "BMS integration": "Integrasjon mot SD-anlegg (BMS)",
  "Commercial refrigeration": "Kommersielle kjøleanlegg",
  "Industrial cooling systems": "Industrielle kjøleanlegg",
  "F-gas certification": "F-gass-sertifisering",
  "Heat pump installation": "Installasjon av varmepumper",
  "Cold room construction": "Bygging av kjølerom",
  "Leak detection and repair": "Lekkasjesøk og reparasjon",
  "Framing / reisverk": "Reisverk",
  "Roof construction": "Takkonstruksjoner",
  "Formwork for concrete": "Forskaling for betong",
  "Window and door installation": "Montering av vinduer og dører",
  "Interior woodwork": "Innvendig snekkerarbeid",
  "Roof boarding and cladding": "Taktro og kledning",
  "Formwork assembly": "Montering av forskaling",
  "Concrete pouring and vibration": "Betongstøp og vibrering",
  "Surface finishing": "Overflatebehandling",
  "Curing and protection": "Herding og beskyttelse",
  "Precast element handling": "Håndtering av betongelementer",
  Shotcrete: "Sprøytebetong",
  "Rebar cutting and bending": "Kapping og bøying av armering",
  "Foundation reinforcement": "Armering av fundamenter",
  "Wall and column rebar": "Armering av vegger og søyler",
  "Slab reinforcement": "Armering av dekker",
  "Reading structural drawings": "Lese konstruksjonstegninger",
  "Tying and placing rebar": "Binding og utlegging av armering",
  "General site labour": "Generelt arbeid på byggeplass",
  Demolition: "Riving",
  "Concrete work": "Betongarbeid",
  "Material handling": "Materialhåndtering",
  "Scaffold assistance": "Hjelp med stillas",
  "Site cleanup": "Rydding av byggeplass",
  "Flat roof membrane": "Takbelegg på flate tak",
  "Pitched roof tiles": "Takstein på skrå tak",
  "Metal roofing": "Metalltak",
  "Gutters and drainage": "Takrenner og nedløp",
  "Roof waterproofing": "Tetting av tak",
  "Green / sedum roof": "Grønne tak (sedum)",
  "System scaffold (Layher/Rux)": "Systemstillas (Layher/Rux)",
  "Facade scaffolding": "Fasadestillas",
  "Industrial scaffolding": "Industristillas",
  "Suspended scaffold": "Hengestillas",
  "Offshore scaffolding": "Offshorestillas",
  "Scaffold inspection": "Stillaskontroll",
  "Interior walls and ceilings": "Innvendige vegger og himlinger",
  "Exterior facades": "Utvendige fasader",
  "Wood surface treatment": "Overflatebehandling av tre",
  "Floor painting and lacquering": "Maling og lakkering av gulv",
  "Wallpaper installation": "Tapetsering",
  "Spray painting": "Sprøytemaling",
  "Interior wet plaster": "Innvendig pussing",
  "Exterior render": "Utvendig puss",
  "Machine plastering": "Maskinpussing",
  "Ceiling plaster": "Pussing av himlinger",
  "Repair and patching": "Reparasjon og flikking",
  "Skim coat finish": "Sparkling",
  "CNC milling": "CNC-fresing",
  "CNC turning": "CNC-dreiing",
  "G-code reading and editing": "Lese og redigere G-kode",
  "Tool setting and offsets": "Verktøyoppsett og offset",
  "Quality measurement": "Kvalitetsmåling",
  "Machine maintenance": "Maskinvedlikehold",
  "Carbon steel pipe welding": "Rørsveising i karbonstål",
  "Stainless pipe welding": "Rørsveising i rustfritt stål",
  "High-pressure systems": "Høytrykkssystemer",
  "ISO 9606 / ASME coded": "ISO 9606 / ASME-sertifisert",
  "Root pass and fill": "Rotstreng og fylling",
  "Offshore pipe welding": "Rørsveising offshore",
  "Ventilation duct fabrication": "Produksjon av ventilasjonskanaler",
  "Facade cladding": "Fasadekledning",
  "Gutters and flashings": "Takrenner og beslag",
  "Stainless fabrication": "Tilvirkning i rustfritt stål",
  "Roof sheet metal": "Tekking med platemetall",
  "Precision cutting and folding": "Presisjonskapping og bretting",
  "Counterbalance forklift": "Motvektstruck",
  "Reach truck": "Skyvemasttruck",
  "Order picker": "Plukktruck",
  "Pallet jack (elektrisk)": "Elektrisk palletruck",
  "Cold storage operation": "Arbeid på kjølelager",
  "Load securing": "Lastsikring",
  "Goods receiving": "Varemottak",
  "Order picking": "Ordreplukk",
  "Inventory counting": "Varetelling",
  "WMS system use": "Bruk av lagerstyringssystem (WMS)",
  "Packing and dispatch": "Pakking og forsendelse",
  "Heavy lifting": "Tunge løft",
  "Tower crane": "Tårnkran",
  "Mobile crane": "Mobilkran",
  "Overhead crane": "Traverskran",
  "Lift planning": "Løfteplanlegging",
  "Slinging and rigging": "Anhuking og rigging",
  "Crane inspection": "Kontroll av kran",
  "Production line operation": "Drift av produksjonslinje",
  "Quality control checks": "Kvalitetskontroll",
  "Machine setup and changeover": "Maskinoppsett og omstilling",
  "Preventive maintenance": "Forebyggende vedlikehold",
  "Safety compliance": "Etterlevelse av sikkerhetskrav",
  "Reporting and logging": "Rapportering og logging",
  "Assembly line work": "Arbeid ved samlebånd",
  "Packing and labelling": "Pakking og merking",
  "Material feeding": "Materialtilførsel",
  "Visual inspection": "Visuell kontroll",
  "Lean / 5S practices": "Lean / 5S",
  "Shift work capability": "Kan jobbe skift",
  "Trenching for pipes/cables": "Grøftegraving for rør og kabler",
  "Foundation excavation": "Utgraving for fundamenter",
  "Road construction": "Veibygging",
  "Mass excavation": "Massegraving",
  "Slope stabilization": "Skråningssikring",
  "GPS-guided excavation": "GPS-styrt graving",
  "Office and commercial cleaning": "Renhold av kontorer og næringsbygg",
  "Industrial cleaning": "Industrirenhold",
  "Window cleaning": "Vindusvask",
  "Floor maintenance (polishing/scrubbing)": "Gulvvedlikehold (polering og skuring)",
  "Chemical handling": "Håndtering av kjemikalier",
  "Night/weekend shifts": "Natt- og helgeskift",
  "Building maintenance": "Bygningsvedlikehold",
  "Minor repairs": "Mindre reparasjoner",
  "Snow clearing": "Snørydding",
  "Waste management": "Avfallshåndtering",
  "Tenant support": "Oppfølging av leietakere",
  "Key and access management": "Nøkler og adgangskontroll",
  "High-rise window cleaning (rope access)": "Vindusvask i høyden (tilkomstteknikk)",
  "Platform/boom lift operation": "Bruk av lift",
  "Interior glass cleaning": "Innvendig glassvask",
  "Facade washing": "Fasadevask",
  "Safety at height": "Sikkerhet ved arbeid i høyden",
  "Chemical use compliance": "Forsvarlig bruk av kjemikalier",
  "Hot kitchen (varmkjøkken)": "Varmkjøkken",
  "Cold kitchen (kaldkjøkken)": "Kaldkjøkken",
  "Bakery and pastry": "Bakst og konditorarbeid",
  "Volume cooking": "Storkjøkken",
  "HACCP compliance": "HACCP",
  "Menu development": "Menyutvikling",
  "Food prep and chopping": "Forberedelse av råvarer",
  Dishwashing: "Oppvask",
  "Stock rotation": "Varerotasjon",
  "Cleaning and hygiene": "Renhold og hygiene",
  "Assisting head chef": "Assistere kjøkkensjefen",
  "Allergen awareness": "Kunnskap om allergener",
  "Table service": "Servering ved bord",
  "Bar service": "Barservering",
  "Upselling and recommendations": "Mersalg og anbefalinger",
  "POS system use": "Bruk av kassesystem",
  "Banquet and event service": "Selskaper og arrangementer",
  "Wine and beverage knowledge": "Kunnskap om vin og drikke",
};

export function skillLabel(lang: RequestLang, skill: string): string {
  if (lang === "en") return skill;
  return SKILL_NB[skill] ?? skill;
}

/** The trade questions as the client reads them, by question id. */
export const TRADE_QUESTION_NB: Record<string, { label: string; help?: string; placeholder?: string }> = {
  fagbrev: { label: "Krav om fagbrev?" },
  forklift: { label: "Krav om truckførerbevis?" },
  machine_cert: { label: "Krav om maskinførerbevis?" },
  site_type: { label: "Type anlegg" },
  tech_drawings: { label: "Må kunne lese tekniske tegninger?" },
  truck_types: { label: "Hvilke trucker skal de kjøre?" },
  warehouse_system: { label: "Trengs erfaring med skanner eller lagersystem?" },
  dsb: { label: "Krav om DSB-autorisasjon?" },
  electrical_work: { label: "Type arbeid" },
  vvs_work: { label: "Type arbeid" },
  own_tools: { label: "Må de ha eget verktøy?" },
  work_at_height: { label: "Arbeid i høyden (stillas, lift)?" },
  welding_methods: { label: "Sveisemetoder" },
  welding_cert: { label: "Krav om sveisesertifikat? (f.eks. ISO 9606)" },
  materials: { label: "Materialer" },
  ysk: { label: "Krav om YSK (yrkessjåførkompetanse)?" },
  adr: { label: "Krav om ADR?" },
  production_type: { label: "Type produksjon" },
  cleaning_type: { label: "Type renhold" },
  cleaning_machines: { label: "Trengs erfaring med renholdsmaskiner?" },
  venue_type: { label: "Type serveringssted" },
  food_hygiene: { label: "Krav om hygienekurs?" },
  hpr: { label: "Krav om norsk autorisasjon (HPR)?" },
  care_setting: { label: "Type tjeneste" },
};

export function tradeQuestionText(
  lang: RequestLang,
  q: { id: string; label: string; help?: string; placeholder?: string },
): { label: string; help?: string; placeholder?: string } {
  if (lang === "en") return { label: q.label, help: q.help, placeholder: q.placeholder };
  const nb = TRADE_QUESTION_NB[q.id];
  if (!nb) return { label: q.label, help: q.help, placeholder: q.placeholder };
  return { label: nb.label, help: nb.help ?? q.help, placeholder: nb.placeholder ?? q.placeholder };
}

/** The "Role details" labels (ALL_ROLE_DETAIL_LABELS), for the review in Norwegian. */
export const ROLE_DETAIL_LABEL_NB: Record<string, string> = {
  "Norwegian at work": "Norsk i arbeidet",
  "Why Norwegian is needed": "Hvorfor norsk trengs",
  "English at work": "Engelsk i arbeidet",
  "Nationalities on the team today": "Nasjonaliteter i arbeidslaget i dag",
  "Language spoken within the team": "Språk i arbeidslaget",
  "Trade certificate (fagbrev) required": "Fagbrev påkrevd",
  "Forklift licence required": "Truckførerbevis påkrevd",
  "Machine operator certificate required": "Maskinførerbevis påkrevd",
  "Type of site": "Type anlegg",
  "Reads technical drawings": "Leser tekniske tegninger",
  "Truck types": "Trucktyper",
  "Warehouse system experience needed": "Erfaring med lagersystem",
  "DSB authorisation required": "DSB-autorisasjon påkrevd",
  "Type of electrical work": "Type elektroarbeid",
  "Type of plumbing and HVAC work": "Type VVS-arbeid",
  "Own tools required": "Eget verktøy påkrevd",
  "Work at height": "Arbeid i høyden",
  "Welding methods": "Sveisemetoder",
  "Welding certificate required": "Sveisesertifikat påkrevd",
  Materials: "Materialer",
  "YSK required": "YSK påkrevd",
  "ADR required": "ADR påkrevd",
  "Type of production": "Type produksjon",
  "Type of cleaning": "Type renhold",
  "Cleaning machine experience needed": "Erfaring med renholdsmaskiner",
  "Type of venue": "Type serveringssted",
  "Food hygiene course required": "Hygienekurs påkrevd",
  "HPR authorisation required": "HPR-autorisasjon påkrevd",
  "Care setting": "Type tjeneste",
  "Worksite address": "Adresse til arbeidsstedet",
  "Staffing project": "Bemanningsprosjekt",
  "Assignment period": "Oppdragsperiode",
  "Hours per week": "Timer per uke",
  "Shift pattern": "Skiftordning",
  "Hours approved on site by": "Timer godkjennes på stedet av",
  "Protective equipment provided by the client": "Verneutstyr stilles av kunden",
  "Probation period": "Prøvetid",
  "Interviewed by": "Intervjues av",
  "Interview rounds": "Intervjurunder",
  "Hire needed by": "Ansettelse innen",
};

/** Rows whose value is what the client typed, a date or a number: shown as written. */
const ROLE_DETAIL_AS_WRITTEN = new Set([
  "Why Norwegian is needed",
  "Nationalities on the team today",
  "Language spoken within the team",
  "Worksite address",
  "Staffing project",
  "Hours per week",
  "Hours approved on site by",
  "Interviewed by",
  "Interview rounds",
  "Hire needed by",
]);

/** One "Role details" row for the review, in the client's language. The stored line stays English. */
export function roleDetailRowLabel(lang: RequestLang, row: { label: string; value: string }): { label: string; value: string } {
  if (lang === "en") return row;
  const label = ROLE_DETAIL_LABEL_NB[row.label] ?? row.label;
  if (ROLE_DETAIL_AS_WRITTEN.has(row.label)) return { label, value: row.value };
  if (row.label === "Assignment period") {
    const w = REQUEST_WORDS.no;
    const both = /^(\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})$/.exec(row.value);
    if (both) return { label, value: fill(w.periodFromTo, { from: both[1], to: both[2] }) };
    const open = /^From (\d{4}-\d{2}-\d{2}), open-ended$/.exec(row.value);
    if (open) return { label, value: fill(w.periodFromOpen, { from: open[1] }) };
    const only = /^From (\d{4}-\d{2}-\d{2})$/.exec(row.value);
    if (only) return { label, value: fill(w.periodFromOnly, { from: only[1] }) };
    return { label, value: row.value };
  }
  return {
    label,
    value: row.value
      .split(", ")
      .map((part) => OPTION_NB[part] ?? part)
      .join(", "),
  };
}
